###
GET http://localhost:8080/items/all


###
POST http://localhost:8080/items/addJSon
Content-Type: application/json

{
  "title": "test2",
  "urlLink": "https://www.dns-shop.ru/product/000014fb2260ed20/156-noutbuk-lenovo-v15-ada-seryj2",
  "imgLink": "test",
  "priceList": [
    {
      "price": 100,
      "date": 1662105897880
    }
  ]
}

###
GET http://localhost:8080/items/4


###
POST http://localhost:8080/items/url/
Content-Type: application/json

{
    "urlLink": "https://www.kasla.ru/catalog/smartfony/samsung/smartfon_samsung_galaxy_s21_fe.html"
}